import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {VERSION} from '../dist/src/save.js';
import {describeBuild} from '../dist/src/services/version.js';
import {ENGINE_VERSION, SAVE_SCHEMA_VERSION} from '../dist/src/compatibility.js';

const assertPackIntegrity = (dir, index, info) => {
  assert.deepEqual(index.requires, {engineVersion: ENGINE_VERSION, saveSchema: SAVE_SCHEMA_VERSION});
  assert.deepEqual(info.pack.integrity, index.integrity);
  for (const file of index.integrity) {
    assert.equal(file.sha256.length, 64);
    const digest = createHash('sha256')
      .update(readFileSync(join(dir, 'maps', file.path)))
      .digest('hex');
    assert.equal(digest, file.sha256, file.id);
  }
};

const containsText = (dir, text) =>
  readdirSync(dir, {withFileTypes: true}).some(entry => {
    const path = join(dir, entry.name);
    return entry.isDirectory() ? containsText(path, text) : readFileSync(path, 'utf8').includes(text);
  });

test('the build copies the game and stamps the commit and save schema', () => {
  const dir = mkdtempSync(join(tmpdir(), 'mossvale build é-'));
  try {
    execFileSync('node', ['scripts/build.mjs'], {
      env: {
        ...process.env,
        BUILD_DIR: dir,
        GITHUB_SHA: 'abcdef0123456789abcdef0123456789abcdef01',
        GITHUB_REF_NAME: 'main',
        MOSSVALE_PORTAL_RETURN_URL: '',
      },
      stdio: 'pipe',
    });
    const info = JSON.parse(readFileSync(join(dir, 'version.json'), 'utf8'));
    const index = JSON.parse(readFileSync(join(dir, 'maps/index.json'), 'utf8'));
    assert.deepEqual([info.short, info.branch, info.saveSchema, info.engineVersion, info.pack.id], ['abcdef0', 'main', VERSION, 1, 'mossvale']);
    assertPackIntegrity(dir, index, info);
    assert.match(info.builtAt, /^\d{4}-\d\d-\d\dT/);
    assert.equal(
      readFileSync(join(dir, 'src/build-config.js'), 'utf8'),
      '// Generated by scripts/build.mjs; do not put credentials here.\nexport const PORTAL_RETURN_URL = "";\n',
    );
    for (const f of ['index.html', 'style.css', 'src/main.js', 'maps/index.json', 'assets/props/tree-oak.png']) assert.equal(existsSync(join(dir, f)), true, f);
  } finally {
    rmSync(dir, {recursive: true, force: true});
  }
});

test('the packaged game receives only the optional public portal URL, never the gate secret', () => {
  const dir = mkdtempSync(join(tmpdir(), 'mossvale portal build '));
  const secret = 'build-only-secret-that-must-never-reach-the-browser';
  try {
    execFileSync('node', ['scripts/build.mjs'], {
      env: {
        ...process.env,
        BUILD_DIR: dir,
        MOSSVALE_PORTAL_RETURN_URL: 'https://zalonline.example/dashboard',
        MOSSVALE_GATE_SECRET: secret,
      },
      stdio: 'pipe',
    });
    const config = readFileSync(join(dir, 'src/build-config.js'), 'utf8');
    assert.equal(
      config,
      '// Generated by scripts/build.mjs; do not put credentials here.\nexport const PORTAL_RETURN_URL = "https://zalonline.example/dashboard";\n',
    );
    assert.equal(containsText(dir, secret), false, 'the gate secret does not appear anywhere in the packaged game');
    assert.equal(readFileSync(join(process.cwd(), 'dist/src/build-config.js'), 'utf8').includes('zalonline.example'), false);
  } finally {
    rmSync(dir, {recursive: true, force: true});
  }
});

test('Vercel builds default to the Zalonline workspace; standalone builds stay unlinked unless configured', () => {
  const dir = mkdtempSync(join(tmpdir(), 'mossvale vercel return '));
  const build = ({vercel, setting}) => {
    const env = {...process.env, BUILD_DIR: dir, GITHUB_SHA: 'abcdef0123456789abcdef0123456789abcdef01'};
    if (vercel) env.VERCEL = '1';
    else delete env.VERCEL;
    if (setting === undefined) delete env.MOSSVALE_PORTAL_RETURN_URL;
    else env.MOSSVALE_PORTAL_RETURN_URL = setting;
    execFileSync('node', ['scripts/build.mjs'], {env, stdio: 'pipe'});
  };
  try {
    build({vercel: true});
    const config = readFileSync(join(dir, 'src/build-config.js'), 'utf8');
    assert.equal(
      config,
      '// Generated by scripts/build.mjs; do not put credentials here.\nexport const PORTAL_RETURN_URL = "https://zalonline.vercel.app/dashboard";\n',
    );
    build({vercel: false});
    assert.match(readFileSync(join(dir, 'src/build-config.js'), 'utf8'), /PORTAL_RETURN_URL = ""/);
    build({vercel: true, setting: ''});
    assert.match(readFileSync(join(dir, 'src/build-config.js'), 'utf8'), /PORTAL_RETURN_URL = ""/);
  } finally {
    rmSync(dir, {recursive: true, force: true});
  }
});

test('an invalid portal return URL is rejected before replacing an existing build directory', () => {
  const dir = mkdtempSync(join(tmpdir(), 'mossvale invalid portal '));
  try {
    writeFileSync(join(dir, 'keep.txt'), 'existing output');
    assert.throws(() =>
      execFileSync('node', ['scripts/build.mjs'], {
        env: {...process.env, BUILD_DIR: dir, MOSSVALE_PORTAL_RETURN_URL: 'javascript:alert(1)'},
        stdio: 'pipe',
      }),
    );
    assert.equal(readFileSync(join(dir, 'keep.txt'), 'utf8'), 'existing output');
  } finally {
    rmSync(dir, {recursive: true, force: true});
  }
});

test('a selected data pack builds as a validated standalone artifact with compatibility metadata', () => {
  const dir = mkdtempSync(join(tmpdir(), 'mossvale selected pack '));
  try {
    const pack = join(process.cwd(), 'tests/fixtures/packs/hearth');
    execFileSync('node', ['scripts/build.mjs', '--pack', pack], {
      env: {...process.env, BUILD_DIR: dir, GITHUB_SHA: '0123456789abcdef0123456789abcdef01234567'},
      stdio: 'pipe',
    });
    const info = JSON.parse(readFileSync(join(dir, 'version.json'), 'utf8'));
    const index = JSON.parse(readFileSync(join(dir, 'maps/index.json'), 'utf8'));
    assert.deepEqual([info.pack.id, info.pack.contentVersion, info.saveSchema], ['hearth-hamlet', 1, VERSION]);
    assertPackIntegrity(dir, index, info);
    assert.deepEqual(index.maps, ['hearth-yard']);
    assert.equal(existsSync(join(dir, 'maps/hearth-yard.json')), true);
    assert.equal(existsSync(join(dir, 'maps/registries.json')), true);
    assert.equal(existsSync(join(dir, 'assets/people/person-red-cap-south.png')), true);
    assert.equal(existsSync(join(dir, 'maps/meadow.json')), false);
  } finally {
    rmSync(dir, {recursive: true, force: true});
  }
});

test('the version label handles a missing stamp', () => {
  assert.equal(describeBuild(null), 'development build');
  assert.match(describeBuild({short: 'abcdef0', builtAt: '2026-10-01T10:00:00Z'}), /^build abcdef0 · 2026-10-01$/);
  assert.match(describeBuild({short: 'abcdef0', dirty: true, builtAt: '2026-10-01T10:00:00Z'}), /abcdef0\+/);
});
