// Frozen saves from earlier builds. A change that stops these loading (or changes what they mean) breaks players'
// progress after an update, so this test fails first. Add a new fixture whenever the save schema gains fields.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {KEYS} from '../dist/src/save.js';
import {level} from '../dist/src/domain/rules.js';
import {codec} from './helpers.mjs';

const fixture = name => readFileSync(new URL(`./fixtures/saves/${name}.json`, import.meta.url), 'utf8').trim();
const load = (key, raw) => {
  const m = new Map([[key, raw]]);
  return codec.load({getItem: k => (m.has(k) ? m.get(k) : null), setItem: (k, v) => m.set(k, String(v))});
};

test('v1 fixture: seen, caught, orbs, wins and XP survive', () => {
  const r = load(KEYS.v1, fixture('v1'));
  assert.equal(r.status, 'migrated');
  assert.deepEqual([r.save.seen, r.save.caught, r.save.orbs, r.save.wins, r.save.met], [[0, 1, 2], [0, 1], 5, 4, true]);
  assert.equal(r.save.team[0].xp, 56);
});

test('v2 fixture: progress, inventory, team records and region survive', () => {
  const r = load(KEYS.v2, fixture('v2'));
  assert.equal(r.status, 'migrated');
  const s = r.save;
  assert.deepEqual([s.region, s.active, s.orbs, s.potions, s.coins, s.badges, s.chests, s.caught, s.wins], [1, 1, 7, 2, 50, [0], [0], [0, 1, 4], 6]);
  assert.deepEqual([level(s, 0), level(s, 1), level(s, 4)], [7, 5, 5]);
  assert.deepEqual(s.party, [1, 0, 4]); // saves from before teams: companion first, then the first captures
});

test('older v3 fixture loads with every saved field intact (new optional fields may appear)', () => {
  const raw = fixture('v3-2026-10');
  const r = load(KEYS.v3, raw);
  assert.equal(r.status, 'ok');
  const resaved = JSON.parse(codec.serialize(r.save));
  for (const [key, value] of Object.entries(JSON.parse(raw))) assert.deepEqual(resaved[key], value, key);
  assert.deepEqual([r.save.party, r.save.goal, r.save.badges, r.save.playTime], [[3, 0, 1], 'amber-seal', [0], 2400]);
});

test('latest v3 fixture loads unchanged and re-saves byte for byte', () => {
  const raw = fixture('v3-latest');
  const r = load(KEYS.v3, raw);
  assert.equal(r.status, 'ok');
  assert.equal(codec.serialize(r.save), raw);
  assert.deepEqual([r.save.hints, r.save.completed, r.save.goal], [['premise', 'capture'], true, 'keeper']);
});

test('a save written by the original build (commit 8fc2c7b, played through its own UI) migrates faithfully', () => {
  // Generated by running that build in a browser: fights, captures and a chest, then reading localStorage. Not hand-written.
  const raw = fixture('v2-original-build');
  const original = JSON.parse(raw);
  const r = load(KEYS.v2, raw);
  assert.equal(r.status, 'migrated');
  const s = r.save;
  assert.deepEqual(
    [s.caught, s.seen, s.chests, s.active, s.orbs, s.potions, s.coins, s.wins, s.met],
    [original.caught, original.seen, original.chests, original.active, original.orbs, original.potions, original.coins, original.wins, original.met],
  );
  for (const id of original.caught) assert.equal(s.team[id].xp, original.team[id].xp, `xp of ${id}`);
  assert.equal(s.team[0].hp, 0, 'a fainted companion stays fainted until rested'); // hp 0 in the original
  assert.equal(s.team[2].hp, original.team[2].hp);
  assert.deepEqual([s.x, s.y], [original.x, original.y]);
  assert.ok(s.party.includes(s.active) && s.party.length === 3 && s.battle === null);
  assert.equal(codec.load({getItem: () => null, setItem() {}}).status, 'new');
});
