// Packages dist/ into build/ with a version stamp, so a playable copy can always be traced to its commit
// and an earlier copy can be put back. No bundling: the game is static files.
//   node scripts/build.mjs            -> build/
//   BUILD_DIR=/tmp/x node scripts/build.mjs
//   node scripts/build.mjs --pack ./content/x        -> a build whose main adventure is the pack in ./content/x
//   node scripts/build.mjs --include ./content/x     -> also offer ./content/x in the adventure chooser (repeatable)
import {createHash} from 'node:crypto';
import {cpSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {dirname, join, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {VERSION} from '../dist/src/save.js';
import {ENGINE_VERSION, SAVE_SCHEMA_VERSION} from '../dist/src/compatibility.js';
import {packFileEntries} from '../dist/src/domain/pack.js';

const repoRoot = fileURLToPath(new URL('../', import.meta.url));
const dist = join(repoRoot, 'dist');
const out = process.env.BUILD_DIR ? resolve(process.env.BUILD_DIR) : join(repoRoot, 'build');
function portalReturnUrl(value) {
  if (!value?.trim()) return '';
  let url;
  try {
    url = new URL(value.trim());
  } catch {
    throw new Error('MOSSVALE_PORTAL_RETURN_URL must be an absolute HTTPS URL (or localhost HTTP URL for development)');
  }
  const localHosts = new Set(['localhost', '127.0.0.1', '[::1]']);
  if ((url.protocol !== 'https:' && !(url.protocol === 'http:' && localHosts.has(url.hostname))) || url.username || url.password)
    throw new Error('MOSSVALE_PORTAL_RETURN_URL must be an absolute HTTPS URL (or localhost HTTP URL for development), without credentials');
  return url.href;
}
const returnUrl = portalReturnUrl(process.env.MOSSVALE_PORTAL_RETURN_URL);
const argIndex = process.argv.indexOf('--pack');
const selectedPack = argIndex >= 0 ? resolve(process.argv[argIndex + 1] ?? '') : process.env.BUILD_PACK ? resolve(process.env.BUILD_PACK) : null;
const includes = process.argv.flatMap((arg, i) => (arg === '--include' ? [resolve(process.argv[i + 1] ?? '')] : []));
function copyDirectory(source, destination) {
  mkdirSync(destination, {recursive: true});
  for (const entry of readdirSync(source, {withFileTypes: true})) {
    const from = join(source, entry.name);
    const to = join(destination, entry.name);
    if (entry.isDirectory()) copyDirectory(from, to);
    else cpSync(from, to);
  }
}
const git = (...args) => {
  try {
    return execFileSync('git', args, {encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore']}).trim();
  } catch {
    return '';
  }
};

const commit = process.env.GITHUB_SHA || git('rev-parse', 'HEAD') || 'unknown';
function validatePackFolder(root) {
  execFileSync(process.execPath, [join(repoRoot, 'scripts/pack.mjs'), 'validate-pack', root], {stdio: 'inherit'});
  const index = JSON.parse(readFileSync(join(root, 'index.json'), 'utf8'));
  if (index.mapDirectory !== undefined && !/^[a-z0-9-]+\/$/.test(index.mapDirectory))
    throw new Error('pack mapDirectory: must be a relative folder ending with /');
  return index;
}
let pack;
execFileSync(process.execPath, [join(repoRoot, 'scripts/validate-assets.mjs')], {stdio: 'inherit'});
if (selectedPack) pack = validatePackFolder(selectedPack);
else execFileSync(process.execPath, [join(repoRoot, 'scripts/validate-maps.mjs')], {stdio: 'inherit'});
const included = includes.map(validatePackFolder);
const info = {
  commit,
  short: commit.slice(0, 7),
  branch: process.env.GITHUB_REF_NAME || git('rev-parse', '--abbrev-ref', 'HEAD') || 'unknown',
  dirty: git('status', '--porcelain') !== '',
  builtAt: new Date().toISOString(),
  saveSchema: VERSION,
  engineVersion: ENGINE_VERSION,
  pack: {
    id: pack?.id ?? 'mossvale',
    contentVersion: Number.isInteger(pack?.contentVersion) && pack.contentVersion > 0 ? pack.contentVersion : 1,
    format: pack?.format ?? 1,
    requires: {engineVersion: ENGINE_VERSION, saveSchema: SAVE_SCHEMA_VERSION},
  },
};

rmSync(out, {recursive: true, force: true});
copyDirectory(dist, out);
writeFileSync(
  join(out, 'src/build-config.js'),
  `// Generated by scripts/build.mjs; do not put credentials here.\nexport const PORTAL_RETURN_URL = ${JSON.stringify(returnUrl)};\n`,
);
/** Copies a validated pack's own files (manifest, registries, objectives, story, maps) into `destination`. */
function copyPack(root, index, destination) {
  rmSync(destination, {recursive: true, force: true});
  mkdirSync(destination, {recursive: true});
  const copyPackFile = name => {
    mkdirSync(dirname(join(destination, name)), {recursive: true});
    cpSync(join(root, name), join(destination, name));
  };
  copyPackFile('index.json');
  copyPackFile(index.registries ?? 'registries.json');
  for (const name of ['objectives', 'story']) if (index[name]) copyPackFile(index[name]);
  const mapDir = index.mapDirectory ?? '';
  for (const id of index.maps) copyPackFile(join(mapDir, id + '.json'));
}
/** Stamps the content version, compatibility and SHA-256 of every file into the copied pack's manifest (the game verifies it on load). */
function stampPack(directory) {
  const indexPath = join(directory, 'index.json');
  const stamped = JSON.parse(readFileSync(indexPath, 'utf8'));
  stamped.contentVersion = Number.isInteger(stamped.contentVersion) && stamped.contentVersion > 0 ? stamped.contentVersion : 1;
  stamped.requires = {engineVersion: ENGINE_VERSION, saveSchema: SAVE_SCHEMA_VERSION};
  stamped.integrity = packFileEntries(stamped).map(({id, path}) => {
    const bytes = readFileSync(join(directory, path));
    return {id, path, sha256: createHash('sha256').update(bytes).digest('hex')};
  });
  writeFileSync(indexPath, JSON.stringify(stamped, null, 2) + '\n');
  return stamped;
}
if (selectedPack) copyPack(selectedPack, pack, join(out, 'maps'));
const outputPack = stampPack(join(out, 'maps'));
// The adventure chooser's catalog: the main adventure in maps/, then every --include under adventures/<id>/.
const catalog = {format: 1, adventures: [{id: outputPack.id, name: outputPack.name, brief: outputPack.brief, path: 'maps/'}]};
included.forEach((index, i) => {
  if (catalog.adventures.some(a => a.id === index.id)) throw new Error(`adventure "${index.id}" is listed twice (--pack/--include)`);
  const destination = join(out, 'adventures', index.id);
  copyPack(includes[i], index, destination);
  stampPack(destination);
  catalog.adventures.push({id: index.id, name: index.name, brief: index.brief, path: `adventures/${index.id}/`});
});
if (selectedPack || includes.length) writeFileSync(join(out, 'adventures.json'), JSON.stringify(catalog, null, 2) + '\n');
info.pack = {...info.pack, id: outputPack.id, contentVersion: outputPack.contentVersion, format: outputPack.format, integrity: outputPack.integrity};
writeFileSync(join(out, 'version.json'), JSON.stringify(info, null, 2) + '\n');
console.log(`built ${info.short}${info.dirty ? ' (uncommitted changes)' : ''} on ${info.branch} (${info.pack.id}) -> ${out}`);
